name = "PlatypusPack"
author = "Wombos Corp"
version = "v2.0.5b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4da000cc8353d7a60efccfbb66783738b93149f6f0bb40f616e872ff0f743d2b"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
