name = "PlatypusPack"
author = "Wombos Corp"
version = "v2.0.5b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6562e704bd4a6cc06d856bb9006343ca1a93d3bd0dbd7b3885c00ae4b660584a"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
