name = "PlatypusPack"
author = "Wombos Corp"
version = "v2.0.5b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "806ac110e2a6063ef282e0a31231f8cde15328a44793fb9f9183eff0e1d5ec6b"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
